licenses(["notice"])  # Apache 2.0

package(
    default_visibility = ["//visibility:public"],
)

load("/third_party/go_tools/go_rules", "go_library")

go_library(
    name = "httpencoding",
    srcs = ["httpencoding.go"],
)
